version: '2.1'

services:
    db:
      container_name: mysqldb
      build:
        context: ./mysql
        dockerfile: Dockerfile
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      ports:
        - "3307:3306"

      healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10        

      environment:
        MYSQL_ROOT_PASSWORD: example
      networks:
        - snet


    account_service:
        container_name: account_service
        restart: always
        build:
          context: ./AccountService
          dockerfile: Dockerfile
        depends_on:
          db:
            condition: service_healthy        
        ports:
          - "8081:8081"
        environment:
          DB_DATABASE: ops
          DB_USER: ops
          DB_PASSWORD: ops
        networks:
          - snet


    analytics_service:
        container_name: analytics_service
        restart: always
        build:
          context: ./AnalyticsService
          dockerfile: Dockerfile
        depends_on:
          db:
            condition: service_healthy        
        ports:
          - "9081:5000"
        volumes:
          - ./AnalyticsService/app:/app          
        environment:
          DB_DATABASE: ops
          DB_USER: ops
          DB_PASSWORD: ops
        networks:
          - snet

networks:
  snet:   
